FROM node:alpine

WORKDIR /app

COPY package.json .
RUN npm install && npm install pm2 -g
COPY pm2.json .
COPY server.js .

EXPOSE 10010

ENTRYPOINT [ "pm2-runtime", "start", "pm2.json", "--env", "production" ]
