name: release version

on:
  push:
    branches:
      - "main"
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy-release:
    name: deploy release
    runs-on: ubuntu-latest
    steps:
    - run: echo success
